import { Contrast,Headphones,Phone,Save,Type } from 'lucide-react'
import { FormEvent,useEffect,useState } from 'react'
import { api } from '../lib/api'

type Preferences={elderMode:boolean;highContrast:boolean;fontScale:number;voiceGuidance:boolean;reducedMotion:boolean;preferredChannel:string}
type NotificationPreferences={emailEnabled:boolean;smsEnabled:boolean;whatsappEnabled:boolean;journeyUpdates:boolean;reminders:boolean;delays:boolean;safeHome:boolean;marketing:boolean}
const defaults:Preferences={elderMode:false,highContrast:false,fontScale:1,voiceGuidance:false,reducedMotion:false,preferredChannel:'in_app'}
const notificationDefaults:NotificationPreferences={emailEnabled:true,smsEnabled:false,whatsappEnabled:false,journeyUpdates:true,reminders:true,delays:true,safeHome:true,marketing:false}

function applyAccessibility(p:Preferences){
  document.documentElement.classList.toggle('elder-mode',p.elderMode)
  document.documentElement.classList.toggle('high-contrast',p.highContrast)
  document.documentElement.classList.toggle('reduced-motion',p.reducedMotion)
  document.documentElement.style.setProperty('--user-font-scale',String(p.fontScale))
  localStorage.setItem('mitdir-accessibility',JSON.stringify(p))
}

export default function Accessibility(){
  const [p,setP]=useState(defaults);const [n,setN]=useState(notificationDefaults);const [notice,setNotice]=useState('');const [error,setError]=useState('')
  useEffect(()=>{void Promise.all([api<{items:Array<Record<string,unknown>>}>('/api/platform?module=preferences'),api<{items:Array<Record<string,unknown>>}>('/api/platform?module=notification_preferences')]).then(([preferences,notifications])=>{const row=preferences.items[0];if(row){const next={elderMode:Boolean(row.elder_mode),highContrast:Boolean(row.high_contrast),fontScale:Number(row.font_scale||1),voiceGuidance:Boolean(row.voice_guidance),reducedMotion:Boolean(row.reduced_motion),preferredChannel:String(row.preferred_channel||'in_app')};setP(next);applyAccessibility(next)}const notify=notifications.items[0];if(notify)setN({emailEnabled:Boolean(notify.email_enabled),smsEnabled:Boolean(notify.sms_enabled),whatsappEnabled:Boolean(notify.whatsapp_enabled),journeyUpdates:Boolean(notify.journey_updates),reminders:Boolean(notify.reminders),delays:Boolean(notify.delays),safeHome:Boolean(notify.safe_home),marketing:Boolean(notify.marketing)})}).catch(e=>setError((e as Error).message))},[])
  async function save(e:FormEvent){e.preventDefault();setError('');try{await Promise.all([api('/api/platform?module=preferences',{method:'POST',body:JSON.stringify(p)}),api('/api/platform?module=notification_preferences',{method:'POST',body:JSON.stringify(n)})]);applyAccessibility(p);setNotice('Accessibility and update preferences saved across your account.')}catch(err){setError((err as Error).message)}}
  function speak(){if(!('speechSynthesis' in window))return setError('Voice guidance is not supported by this browser.');speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance('MitDir elder friendly mode. Use the large navigation menu to open bookings, live journeys, messages, or telephone help.'))}
  return <div className="portal-page"><div className="module-heading"><div><span className="portal-kicker">Personal accessibility</span><h1>Elder-friendly mode</h1><p>Make MitDir easier to read, hear and operate without changing anyone else’s view.</p></div><a className="button" href="tel:+493012345678"><Phone/>One-tap help</a></div>{notice&&<div className="portal-notice"><Save/><span>{notice}</span></div>}{error&&<div className="portal-error">{error}</div>}
    <form className="accessibility-grid" onSubmit={save}><section className="portal-panel"><div className="settings-title"><span><Type/></span><div><h2>Display</h2><p>Typography and visual contrast</p></div></div><label className="toggle-row"><span><strong>Simple, larger screens</strong><small>Increase labels, controls and spacing.</small></span><input type="checkbox" checked={p.elderMode} onChange={e=>setP({...p,elderMode:e.target.checked})}/></label><label className="toggle-row"><span><strong>High contrast</strong><small>Strengthen colour and border contrast.</small></span><input type="checkbox" checked={p.highContrast} onChange={e=>setP({...p,highContrast:e.target.checked})}/></label><label className="range-row"><span><strong>Text size</strong><small>{Math.round(p.fontScale*100)}%</small></span><input type="range" min="1" max="1.5" step="0.1" value={p.fontScale} onChange={e=>setP({...p,fontScale:Number(e.target.value)})}/></label></section>
      <section className="portal-panel"><div className="settings-title"><span><Headphones/></span><div><h2>Guidance</h2><p>Voice, motion and contact preferences</p></div></div><label className="toggle-row"><span><strong>Voice guidance</strong><small>Offer spoken navigation help.</small></span><input type="checkbox" checked={p.voiceGuidance} onChange={e=>setP({...p,voiceGuidance:e.target.checked})}/></label><button type="button" className="accessibility-test" onClick={speak}><Headphones/>Test voice guidance</button><label className="toggle-row"><span><strong>Reduce motion</strong><small>Minimise animated transitions.</small></span><input type="checkbox" checked={p.reducedMotion} onChange={e=>setP({...p,reducedMotion:e.target.checked})}/></label><label className="field"><span>Preferred update channel</span><select value={p.preferredChannel} onChange={e=>setP({...p,preferredChannel:e.target.value})}><option value="in_app">In-app</option><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option><option value="phone">Telephone</option></select></label></section>
      <section className="portal-panel notification-preferences"><div className="settings-title"><span><Phone/></span><div><h2>Family update rules</h2><p>Choose channels and which operational events may notify you.</p></div></div>{([['emailEnabled','Email updates'],['smsEnabled','SMS updates'],['whatsappEnabled','WhatsApp updates'],['journeyUpdates','Journey milestones'],['reminders','Booking reminders'],['delays','Delay alerts'],['safeHome','Safe-home confirmation']] as Array<[keyof NotificationPreferences,string]>).map(([key,label])=><label className="toggle-row" key={key}><span><strong>{label}</strong><small>{key.endsWith('Enabled')?'Used when the provider is connected.':'Keep this event enabled for your care circle.'}</small></span><input type="checkbox" checked={n[key]} onChange={e=>setN({...n,[key]:e.target.checked})}/></label>)}</section><div className="accessibility-preview portal-panel"><Contrast/><span><strong>Preview</strong><small>Your changes apply when you save.</small></span><button className="button"><Save/>Save preferences</button></div></form>
  </div>
}
