import { Bot,CheckCircle2,Clock3,Send,ShieldCheck,Sparkles } from 'lucide-react'
import { FormEvent,useEffect,useState } from 'react'
import { api,dateTime } from '../lib/api'

type Row=Record<string,unknown>
const jobs=[['booking_draft','Draft a booking from a call'],['journey_summary','Summarise a completed journey'],['partner_match_explanation','Explain a suggested match'],['incident_summary','Summarise and classify an incident'],['translation','Translate a family message'],['operations_forecast','Forecast operational demand'],['voice_booking','Voice-booking transcript to draft']] as const

export default function AiStudio(){
  const [configured,setConfigured]=useState(false);const [history,setHistory]=useState<Row[]>([]);const [jobType,setJobType]=useState<(typeof jobs)[number][0]>('booking_draft');const [text,setText]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false)
  async function load(){const r=await api<{configured:boolean;items:Row[]}>('/api/ai');setConfigured(r.configured);setHistory(r.items)}
  useEffect(()=>{void Promise.resolve().then(load).catch(e=>setError((e as Error).message))},[])
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await api<{item:Row;configured:boolean}>('/api/ai',{method:'POST',body:JSON.stringify({jobType,input:{text}})});setNotice(r.configured?'AI task completed.':'Draft saved. Add GROQ_API_KEY later to process it with Groq.');setText('');await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <div className="portal-page"><div className="module-heading"><div><span className="portal-kicker">Administrative AI</span><h1>MitDir AI concierge</h1><p>Draft, summarise, translate and forecast—always non-clinical and under human review.</p></div><span className={`ai-status ${configured?'connected':''}`}>{configured?<CheckCircle2/>:<Clock3/>}{configured?'Groq connected':'Groq key pending'}</span></div>{notice&&<div className="portal-notice"><Sparkles/><span>{notice}</span></div>}{error&&<div className="portal-error">{error}</div>}
    <div className="ai-layout"><form className="portal-panel ai-composer" onSubmit={submit}><div className="settings-title"><span><Bot/></span><div><h2>New assisted task</h2><p>A human approves every output before it becomes operational.</p></div></div><label className="field"><span>Task</span><select value={jobType} onChange={e=>setJobType(e.target.value as typeof jobType)}>{jobs.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Source notes or transcript</span><textarea required rows={10} value={text} onChange={e=>setText(e.target.value)} placeholder="Paste the telephone transcript, journey notes, incident record or message here…"/></label><div className="ai-guardrail"><ShieldCheck/><span><strong>Administrative support only</strong><small>No diagnosis, prescription, clinical advice, or unsupervised safeguarding decisions.</small></span></div><button className="button" disabled={busy}>{busy?'Processing…':configured?'Create assisted draft':'Save provider-ready draft'}<Send/></button></form><section className="portal-panel"><div className="panel-title"><div><span>Recent work</span><h2>AI task history</h2></div></div><div className="ai-history">{history.map(item=><article key={String(item.id)}><span className={`table-badge table-badge--${item.status}`}>{String(item.status).replaceAll('_',' ')}</span><strong>{String(item.job_type).replaceAll('_',' ')}</strong><small>{dateTime(String(item.created_at))}</small>{Boolean(item.output)&&<p>{String((item.output as Row).text||JSON.stringify(item.output))}</p>}</article>)}{!history.length&&<div className="empty-state"><Bot/><strong>No assisted tasks yet</strong><span>Your approved drafts and summaries will appear here.</span></div>}</div></section></div>
  </div>
}
