import { ArrowLeft,ArrowRight,Check,Eye,EyeOff,LockKeyhole,Mail,ShieldCheck } from 'lucide-react'
import { FormEvent,useState } from 'react'
import { Link,useLocation,useNavigate } from 'react-router-dom'
import Logo from '../components/Logo'
import { useAuth } from '../lib/auth'

export default function Login(){
  const {login}=useAuth();const navigate=useNavigate();const location=useLocation();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await login(email,password);navigate((location.state as {from?:string})?.from||'/app')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <main className="auth-page"><section className="auth-brand"><div><Logo light/><div className="auth-brand__copy"><span>One coordinated platform</span><h1>Care, clarity and control in one place.</h1><p>Manage every request, journey, permission and update from a secure role-based workspace.</p></div><div className="auth-points"><span><Check/>Real-time journey oversight</span><span><Check/>Role-based access and consent</span><span><Check/>Secure operational records</span></div></div></section><section className="auth-form-wrap"><div className="auth-form"><Link to="/" className="back-link"><ArrowLeft/>Back to website</Link><div className="auth-form__heading"><span><ShieldCheck/></span><h2>Welcome back</h2><p>Sign in to your MitDir workspace.</p></div>{error&&<div className="form-error">{error}</div>}<form onSubmit={submit}><label className="field"><span>Email address</span><div className="input-with-icon"><Mail/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></div></label><label className="field"><span>Password</span><div className="input-with-icon auth-password"><LockKeyhole/><input type={show?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/><button type="button" onClick={()=>setShow(!show)} aria-label="Show password">{show?<EyeOff/>:<Eye/>}</button></div></label><div className="auth-options"><label><input type="checkbox"/>Remember me</label><button type="button" onClick={async()=>{if(!email){setError('Enter your email first');return}try{await fetch('/api/auth?action=forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});setError('If the account exists, a reset request has been recorded.')}catch{setError('Unable to request a reset')}}}>Forgot password?</button></div><button className="button auth-submit" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowRight/></button></form><p className="auth-register">New to MitDir? <Link to="/register">Create an account</Link></p><div className="auth-security"><ShieldCheck/>Protected by encrypted sessions and role-based permissions.</div></div></section></main>
}
