import { LockKeyhole,MessageCircle,Plus,Send } from 'lucide-react'
import { FormEvent,useCallback,useEffect,useState } from 'react'
import { api,dateTime } from '../lib/api'

type Row=Record<string,unknown>
export default function Messages(){
  const [conversations,setConversations]=useState<Row[]>([]);const [selected,setSelected]=useState('');const [messages,setMessages]=useState<Row[]>([]);const [body,setBody]=useState('');const [subject,setSubject]=useState('');const [error,setError]=useState('');const [creating,setCreating]=useState(false)
  const loadConversations=useCallback(async(chooseFirst=false)=>{const r=await api<{items:Row[]}>('/api/platform?module=conversations');setConversations(r.items);if(chooseFirst&&r.items[0])setSelected(String(r.items[0].id))},[])
  useEffect(()=>{void Promise.resolve().then(()=>loadConversations(true)).catch(e=>setError((e as Error).message))},[loadConversations])
  useEffect(()=>{if(!selected)return;void api<{items:Row[]}>(`/api/platform?module=messages&conversationId=${selected}`).then(r=>setMessages(r.items)).catch(e=>setError((e as Error).message))},[selected])
  async function send(e:FormEvent){e.preventDefault();if(!body.trim())return;try{await api('/api/platform?module=messages',{method:'POST',body:JSON.stringify({conversationId:selected,body})});setBody('');const r=await api<{items:Row[]}>(`/api/platform?module=messages&conversationId=${selected}`);setMessages(r.items);await loadConversations()}catch(err){setError((err as Error).message)}}
  async function create(e:FormEvent){e.preventDefault();try{const r=await api<{item:Row}>('/api/platform?module=conversations',{method:'POST',body:JSON.stringify({subject,message:body||undefined})});setCreating(false);setSubject('');setBody('');await loadConversations();setSelected(String(r.item.id))}catch(err){setError((err as Error).message)}}
  return <div className="portal-page"><div className="module-heading"><div><span className="portal-kicker">Private communication</span><h1>Secure messages</h1><p>Booking-specific chat keeps personal telephone numbers private.</p></div><button className="button" onClick={()=>setCreating(true)}><Plus/>New conversation</button></div>{error&&<div className="portal-error">{error}</div>}
    <div className="message-shell portal-panel"><aside><div className="message-security"><LockKeyhole/><span><strong>Protected workspace</strong><small>Only conversation members can read messages.</small></span></div>{conversations.map(item=><button className={selected===String(item.id)?'active':''} key={String(item.id)} onClick={()=>setSelected(String(item.id))}><span><strong>{String(item.subject)}</strong><small>{String(item.last_message||item.senior||'No messages yet')}</small></span>{Boolean(item.last_message_at)&&<time>{dateTime(String(item.last_message_at))}</time>}</button>)}</aside><section>{selected?<><div className="message-feed">{messages.map(item=><article key={String(item.id)}><div><strong>{String(item.sender||'MitDir member')}</strong><time>{dateTime(String(item.created_at))}</time></div><p>{String(item.body)}</p>{Boolean(item.translated_body)&&<small>Translation: {String(item.translated_body)}</small>}</article>)}{!messages.length&&<div className="empty-state"><MessageCircle/><strong>Start the conversation</strong><span>Messages stay linked to this care relationship.</span></div>}</div><form className="message-compose" onSubmit={send}><textarea aria-label="Message" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a secure message…"/><button className="button" aria-label="Send message"><Send/></button></form></>:<div className="empty-state"><MessageCircle/><strong>Select a conversation</strong><span>Your secure messages will appear here.</span></div>}</section></div>
    {creating&&<div className="portal-modal"><form className="portal-modal__card" onSubmit={create}><span className="portal-kicker">Secure conversation</span><h2>Start a conversation</h2><label className="field"><span>Subject</span><input required value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="field"><span>First message (optional)</span><textarea rows={4} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="portal-modal__actions"><button type="button" onClick={()=>setCreating(false)}>Cancel</button><button className="button">Create</button></div></form></div>}
  </div>
}
