import { AlertTriangle,CalendarCheck,Check,ChevronDown,Filter,Plus,RefreshCcw,Search,X } from 'lucide-react'
import { FormEvent,useCallback,useEffect,useMemo,useState } from 'react'
import { useParams } from 'react-router-dom'
import { api,dateTime,money } from '../lib/api'
import { useAuth,type Role } from '../lib/auth'

type Row=Record<string,unknown>
type Source='seniors'|'bookings'|'partners'|'services'|'organizations'
type Field={key:string;label:string;type?:'text'|'email'|'number'|'datetime-local'|'textarea'|'select'|'url';options?:string[];source?:Source;optional?:boolean}
type Config={title:string;description:string;module:string;columns:Array<[string,string]>;createLabel?:string;fields?:Field[];createRoles?:Role[];status?:string[];statusKey?:'status'|'verificationStatus';moneyKeys?:string[]}

const admin:Role[]=['admin','operations']
const configs:Record<string,Config>={
  'care-circle':{title:'Care circle',description:'Invite relatives and trusted contacts with clear responsibilities and separate permissions.',module:'care_circle',columns:[['senior','Older adult'],['name','Contact'],['relationship','Relationship'],['responsibilities','Responsibilities'],['invited_email','Email'],['status','Access']],createLabel:'Invite contact',createRoles:['admin','operations','family','senior'],fields:[{key:'seniorId',label:'Older adult',type:'select',source:'seniors'},{key:'name',label:'Contact name'},{key:'invitedEmail',label:'Email',type:'email',optional:true},{key:'relationship',label:'Relationship'},{key:'responsibilities',label:'Responsibilities (comma separated)',optional:true}]},
  availability:{title:'Availability calendar',description:'Publish working hours, holidays and service areas; families can see genuine open times.',module:'availability',columns:[['partner','Partner'],['starts_at','Starts'],['ends_at','Ends'],['slot_type','Type'],['service_area','Service area'],['notes','Notes']],createLabel:'Add calendar slot',createRoles:['admin','operations','partner'],fields:[{key:'partnerId',label:'Partner (admins only)',type:'select',source:'partners',optional:true},{key:'startsAt',label:'Starts',type:'datetime-local'},{key:'endsAt',label:'Ends',type:'datetime-local'},{key:'slotType',label:'Slot type',type:'select',options:['available','unavailable','holiday','reserved']},{key:'serviceArea',label:'Service area',optional:true},{key:'notes',label:'Notes',type:'textarea',optional:true}]},
  safety:{title:'Safety centre',description:'SOS, missed-arrival, overdue-journey and safeguarding escalation in one operational queue.',module:'safety_alerts',columns:[['created_at','Raised'],['alert_type','Alert'],['severity','Severity'],['senior','Older adult'],['booking_number','Booking'],['details','Details'],['status','Status']],createLabel:'Raise safety alert',createRoles:['admin','operations','family','senior','partner','care_home'],fields:[{key:'bookingId',label:'Related booking',type:'select',source:'bookings',optional:true},{key:'seniorId',label:'Older adult',type:'select',source:'seniors',optional:true},{key:'alertType',label:'Alert type',type:'select',options:['sos','missed_arrival','overdue_journey','welfare_check','other']},{key:'severity',label:'Severity',type:'select',options:['medium','high','critical']},{key:'details',label:'What happened?',type:'textarea',optional:true}],status:['open','acknowledged','escalated','resolved','false_alarm']},
  documents:{title:'Secure document vault',description:'Keep appointment letters, consent evidence and authorised instructions linked to the right person.',module:'documents',columns:[['created_at','Added'],['name','Document'],['document_type','Type'],['senior','Older adult'],['booking_number','Booking'],['access_scope','Access'],['expires_at','Expires']],createLabel:'Add document record',createRoles:['admin','operations','family','senior','partner','care_home'],fields:[{key:'seniorId',label:'Older adult',type:'select',source:'seniors',optional:true},{key:'bookingId',label:'Booking',type:'select',source:'bookings',optional:true},{key:'name',label:'Document name'},{key:'documentType',label:'Document type'},{key:'fileUrl',label:'Secure file URL',type:'url',optional:true},{key:'accessScope',label:'Who can access it?',type:'select',options:['private','care_circle','assigned_partner','operations']},{key:'expiresAt',label:'Expires',type:'datetime-local',optional:true}]},
  consents:{title:'Electronic consent',description:'Sign time-limited task permissions, review expiry and revoke consent at any time.',module:'consent_records',columns:[['booking_number','Booking'],['senior','Older adult'],['permission','Permission'],['signature_name','Signed by'],['signed_at','Signed'],['expires_at','Expires'],['consent_status','Status']],createLabel:'Sign consent',createRoles:['admin','operations','family','senior','care_home'],fields:[{key:'bookingId',label:'Booking',type:'select',source:'bookings'},{key:'seniorId',label:'Older adult',type:'select',source:'seniors'},{key:'permission',label:'Permission granted',type:'textarea'},{key:'signatureName',label:'Electronic signature (full name)'},{key:'expiresAt',label:'Expires',type:'datetime-local'}],status:['active','expired','revoked']},
  medication:{title:'Medication collections',description:'Record collection authority and handover without giving clinical advice.',module:'medication_collections',columns:[['created_at','Created'],['senior','Older adult'],['pharmacy_name','Pharmacy'],['collection_reference','Reference'],['collector','Collector'],['status','Status'],['delivered_at','Delivered']],createLabel:'Record collection',createRoles:['admin','operations','family','senior','partner'],fields:[{key:'seniorId',label:'Older adult',type:'select',source:'seniors'},{key:'bookingId',label:'Booking',type:'select',source:'bookings',optional:true},{key:'pharmacyName',label:'Pharmacy'},{key:'collectionReference',label:'Collection reference',optional:true},{key:'notes',label:'Authorised instructions only',type:'textarea',optional:true}],status:['requested','authorised','collected','delivered','cancelled']},
  recurring:{title:'Recurring support',description:'Plan weekly companionship, collections, shopping and repeat appointments with continuity preference.',module:'recurring_plans',columns:[['senior','Older adult'],['service','Service'],['recurrence_rule','Schedule'],['next_occurrence','Next visit'],['preferred_partner','Preferred partner'],['pickup_address','Address'],['status','Status']],createLabel:'Create recurring plan',createRoles:['admin','operations','family','senior','care_home'],fields:[{key:'seniorId',label:'Older adult',type:'select',source:'seniors'},{key:'serviceId',label:'Service',type:'select',source:'services'},{key:'preferredPartnerId',label:'Preferred partner',type:'select',source:'partners',optional:true},{key:'recurrenceRule',label:'Schedule (for example: every Tuesday)'},{key:'nextOccurrence',label:'First occurrence',type:'datetime-local'},{key:'pickupAddress',label:'Pickup address'},{key:'durationMinutes',label:'Duration in minutes',type:'number'},{key:'notes',label:'Notes',type:'textarea',optional:true}],status:['active','paused','completed','cancelled']},
  onboarding:{title:'Partner onboarding',description:'Track identity, training and compliance documents with verification and expiry checks.',module:'partner_documents',columns:[['partner','Partner'],['document_type','Document'],['verification_status','Verification'],['expires_at','Expires'],['reviewed_at','Reviewed'],['created_at','Uploaded']],createLabel:'Add verification document',createRoles:['admin','operations','partner'],fields:[{key:'partnerId',label:'Partner (admins only)',type:'select',source:'partners',optional:true},{key:'documentType',label:'Document type'},{key:'fileUrl',label:'Secure file URL',type:'url',optional:true},{key:'expiresAt',label:'Expires',type:'datetime-local',optional:true}],status:['pending','verified','rejected','expired'],statusKey:'verificationStatus'},
  shifts:{title:'Shift planner',description:'Plan partner work, service areas and replacement workflows.',module:'shifts',columns:[['partner','Partner'],['starts_at','Starts'],['ends_at','Ends'],['service_area','Area'],['replacement_partner','Replacement'],['status','Status'],['notes','Notes']],createLabel:'Plan shift',createRoles:['admin','operations','partner'],fields:[{key:'partnerId',label:'Partner (admins only)',type:'select',source:'partners',optional:true},{key:'startsAt',label:'Starts',type:'datetime-local'},{key:'endsAt',label:'Ends',type:'datetime-local'},{key:'serviceArea',label:'Service area',optional:true},{key:'notes',label:'Notes',type:'textarea',optional:true}],status:['scheduled','confirmed','in_progress','completed','cancelled']},
  'service-areas':{title:'Service areas',description:'Control postal-code coverage, partner travel distance, mileage and base travel fees.',module:'service_areas',columns:[['name','Area'],['postal_codes','Postal codes'],['base_travel_fee_cents','Base travel fee'],['per_km_cents','Per kilometre'],['active','Active'],['created_at','Created']],createLabel:'Add service area',createRoles:admin,fields:[{key:'name',label:'Area name'},{key:'postalCodes',label:'Postal codes (comma separated)'},{key:'baseTravelFeeCents',label:'Base travel fee in cents',type:'number'},{key:'perKmCents',label:'Per kilometre in cents',type:'number'}],moneyKeys:['base_travel_fee_cents','per_km_cents']},
  pricing:{title:'Pricing rules',description:'Manage base, mileage, evening, weekend and cancellation policies with a transparent audit trail.',module:'pricing_rules',columns:[['name','Rule'],['service','Service'],['rule_type','Type'],['amount_cents','Amount'],['percentage','Percentage'],['active','Active'],['created_at','Created']],createLabel:'Add pricing rule',createRoles:admin,fields:[{key:'name',label:'Rule name'},{key:'serviceId',label:'Service',type:'select',source:'services',optional:true},{key:'ruleType',label:'Rule type',type:'select',options:['base','hourly','mileage','evening','weekend','cancellation']},{key:'amountCents',label:'Amount in cents',type:'number'},{key:'percentage',label:'Percentage',type:'number',optional:true}],moneyKeys:['amount_cents']},
  promotions:{title:'Promotions & credits',description:'Manage discount codes, service credits and gift-voucher campaigns.',module:'promotions',columns:[['code','Code'],['description','Description'],['discount_type','Type'],['value','Value'],['uses','Used'],['max_uses','Limit'],['ends_at','Ends'],['active','Active']],createLabel:'Create promotion',createRoles:admin,fields:[{key:'code',label:'Code'},{key:'description',label:'Description',optional:true},{key:'discountType',label:'Discount type',type:'select',options:['fixed','percentage','credit']},{key:'value',label:'Value',type:'number'},{key:'startsAt',label:'Starts',type:'datetime-local',optional:true},{key:'endsAt',label:'Ends',type:'datetime-local',optional:true},{key:'maxUses',label:'Maximum uses',type:'number',optional:true}]},
  memberships:{title:'Memberships & contracts',description:'Monthly family memberships and organisation contracts, ready for a connected payment provider.',module:'subscriptions',columns:[['plan_name','Plan'],['subscriber','Subscriber'],['organization','Organisation'],['interval','Interval'],['amount_cents','Amount'],['status','Status'],['current_period_end','Renews']],createLabel:'Start membership',createRoles:['admin','operations','family','senior','care_home'],fields:[{key:'planName',label:'Plan name'},{key:'interval',label:'Interval',type:'select',options:['monthly','annual']},{key:'amountCents',label:'Amount in cents',type:'number'},{key:'organizationId',label:'Organisation',type:'select',source:'organizations',optional:true}],status:['pending','active','paused','cancelled','past_due'],moneyKeys:['amount_cents']},
  invoices:{title:'Invoices & accounting',description:'VAT-ready invoices, payment records, refunds and downloadable accounting data.',module:'invoices',columns:[['invoice_number','Invoice'],['customer','Customer'],['organization','Organisation'],['issued_at','Issued'],['due_at','Due'],['total_cents','Total'],['status','Status']],moneyKeys:['total_cents']},
  ratings:{title:'Ratings & continuity',description:'Measure family satisfaction and help families book the same trusted partner again.',module:'ratings',columns:[['created_at','Submitted'],['booking_number','Booking'],['partner','Partner'],['reviewer','Reviewer'],['score','Score'],['would_book_again','Book again'],['comment','Comment']]},
  communications:{title:'Communication delivery',description:'Track in-app, email, SMS and WhatsApp updates, reminders and safe-home alerts.',module:'communications',columns:[['created_at','Created'],['recipient','Recipient'],['booking_number','Booking'],['channel','Channel'],['template','Message'],['status','Delivery'],['sent_at','Sent']]},
  integrations:{title:'Integrations',description:'Connect communications, payments, secure storage and AI providers when their credentials are ready.',module:'integrations',columns:[['name','Capability'],['provider','Provider'],['configured','Connected']]},
}

export default function PlatformModule(){
  const {module='care-circle'}=useParams();const config=configs[module]||configs['care-circle'];const {user}=useAuth()
  const [items,setItems]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('');const [open,setOpen]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError('');try{setItems((await api<{items:Row[]}>(`/api/platform?module=${config.module}`)).items)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[config.module])
  useEffect(()=>{void Promise.resolve().then(load)},[load])
  const filtered=useMemo(()=>items.filter(row=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),[items,search])
  const canCreate=Boolean(config.fields&&user&&config.createRoles?.includes(user.role))
  async function update(row:Row,value:string){if(config.module==='consent_records'&&value==='active')return;const body:Row={id:row.id};if(config.statusKey==='verificationStatus')body.verificationStatus=value;else body.status=value;await api(`/api/platform?module=${config.module}`,{method:'PATCH',body:JSON.stringify(body)});await load()}
  return <div className="portal-page"><div className="module-heading"><div><span className="portal-kicker">Connected care workspace</span><h1>{config.title}</h1><p>{config.description}</p></div>{canCreate&&<button className="button" onClick={()=>setOpen(true)}><Plus/>{config.createLabel}</button>}</div>
    {module==='medication'&&<div className="platform-callout"><AlertTriangle/><span><strong>Administrative record only.</strong> MitDir does not provide medication or clinical advice.</span></div>}
    <section className="portal-panel module-table-panel"><div className="module-toolbar"><div className="module-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}…`}/></div><button><Filter/>Filter<ChevronDown/></button><button onClick={load}><RefreshCcw/>Refresh</button><span>{filtered.length} records</span></div>
      {error?<div className="portal-error">{error}</div>:loading?<div className="module-loading"><i/><span>Loading {config.title.toLowerCase()}…</span></div>:<div className="module-table-wrap"><table className="module-table"><thead><tr>{config.columns.map(([key,label])=><th key={key}>{label}</th>)}{config.status&&<th>Action</th>}</tr></thead><tbody>{filtered.map((row,index)=><tr key={String(row.id||index)}>{config.columns.map(([key])=><td key={key}>{renderValue(key,row[key],config)}</td>)}{config.status&&<td><select className="table-select" value={String(row.consent_status||row.status||row.verification_status||'pending')} onChange={e=>void update(row,e.target.value)}>{config.status.map(s=><option key={s}>{s}</option>)}</select></td>}</tr>)}</tbody></table>{!filtered.length&&<div className="empty-state"><CalendarCheck/><strong>No records yet</strong><span>Create the first record or adjust your search.</span></div>}</div>}
    </section>{open&&config.fields&&<PlatformDialog config={config} onClose={()=>setOpen(false)} onCreated={()=>{setOpen(false);void load()}}/>}
  </div>
}

function renderValue(key:string,value:unknown,config:Config){
  if(value===null||value===undefined||value==='')return <span className="muted">—</span>
  if(config.moneyKeys?.includes(key))return money(Number(value))
  if(key.endsWith('_at')||key.endsWith('_date')||key==='next_occurrence')return dateTime(String(value))
  if(typeof value==='boolean')return value?<span className="table-check"><Check/>Yes</span>:<span className="muted">No</span>
  if(Array.isArray(value))return value.join(', ')
  if(typeof value==='object')return Object.entries(value as Row).filter(([,v])=>v).map(([k])=>k.replaceAll('_',' ')).join(', ')||'—'
  if(['status','consent_status','severity','slot_type','verification_status','alert_type','channel','discount_type','rule_type'].includes(key))return <span className={`table-badge table-badge--${String(value)}`}>{String(value).replaceAll('_',' ')}</span>
  return String(value)
}

function PlatformDialog({config,onClose,onCreated}:{config:Config;onClose:()=>void;onCreated:()=>void}){
  const [values,setValues]=useState<Record<string,string>>({});const [lookups,setLookups]=useState<Partial<Record<Source,Row[]>>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  useEffect(()=>{const sources=[...new Set(config.fields?.flatMap(f=>f.source?[f.source]:[])||[])];void Promise.all(sources.map(async source=>{try{const result=await api<{items:Row[]}>(`/api/data?module=${source}`);setLookups(prev=>({...prev,[source]:result.items}))}catch{setLookups(prev=>({...prev,[source]:[]}))}}))},[config.fields])
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body:Record<string,unknown>={...values};if(typeof body.responsibilities==='string')body.responsibilities=body.responsibilities.split(',').map(v=>v.trim()).filter(Boolean);if(typeof body.postalCodes==='string')body.postalCodes=body.postalCodes.split(',').map(v=>v.trim()).filter(Boolean);await api(`/api/platform?module=${config.module}`,{method:'POST',body:JSON.stringify(body)});onCreated()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <div className="portal-modal" role="dialog" aria-modal="true"><div className="portal-modal__card"><button className="portal-modal__close" onClick={onClose}><X/></button><span className="portal-kicker">New record</span><h2>{config.createLabel}</h2><p>Only the people with the right role and relationship will be able to see it.</p>{error&&<div className="form-error">{error}</div>}<form onSubmit={submit}>{config.fields!.map(field=><label className="field" key={field.key}><span>{field.label}</span>{field.source?<select required={!field.optional} value={values[field.key]||''} onChange={e=>setValues({...values,[field.key]:e.target.value})}><option value="">{field.optional?'None':'Select…'}</option>{(lookups[field.source]||[]).map(row=><option key={String(row.id)} value={String(row.id)}>{lookupLabel(field.source!,row)}</option>)}</select>:field.type==='select'?<select required={!field.optional} value={values[field.key]||''} onChange={e=>setValues({...values,[field.key]:e.target.value})}><option value="">Select…</option>{field.options?.map(o=><option key={o} value={o}>{o.replaceAll('_',' ')}</option>)}</select>:field.type==='textarea'?<textarea required={!field.optional} rows={4} value={values[field.key]||''} onChange={e=>setValues({...values,[field.key]:e.target.value})}/>:<input required={!field.optional} type={field.type||'text'} value={values[field.key]||''} onChange={e=>setValues({...values,[field.key]:e.target.value})}/>}</label>)}<div className="portal-modal__actions"><button type="button" onClick={onClose}>Cancel</button><button className="button" disabled={busy}>{busy?'Saving…':'Save record'}</button></div></form></div></div>
}

function lookupLabel(source:Source,row:Row){if(source==='bookings')return `${row.booking_number||'Booking'} · ${row.senior||row.service||''}`;if(source==='services')return String(row.name);if(source==='partners')return String(row.name);if(source==='organizations')return String(row.name);return String(row.display_name||row.name||'Older adult')}
