import { ArrowLeft,ArrowRight,HeartHandshake,UserRound } from 'lucide-react'
import { FormEvent,useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import Logo from '../components/Logo'
import { useAuth } from '../lib/auth'

export default function Register(){
  const {register}=useAuth();const navigate=useNavigate();const [form,setForm]=useState({name:'',email:'',phone:'',password:'',role:'family' as 'family'|'senior'});const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await register(form);navigate('/app')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <main className="auth-page"><section className="auth-brand auth-brand--register"><div><Logo light/><div className="auth-brand__copy"><span>Join MitDir</span><h1>Support begins with one simple account.</h1><p>Create a secure workspace for yourself or your family. Professional and care-home accounts are invited by an administrator.</p></div></div></section><section className="auth-form-wrap"><div className="auth-form auth-form--register"><Link to="/" className="back-link"><ArrowLeft/>Back to website</Link><div className="auth-form__heading"><span><UserRound/></span><h2>Create your account</h2><p>Choose who the account is for and add your details.</p></div>{error&&<div className="form-error">{error}</div>}<form onSubmit={submit}><div className="auth-role-choice"><button type="button" className={form.role==='family'?'active':''} onClick={()=>setForm({...form,role:'family'})}><HeartHandshake/><strong>Family member</strong><small>Arrange care for a loved one</small></button><button type="button" className={form.role==='senior'?'active':''} onClick={()=>setForm({...form,role:'senior'})}><UserRound/><strong>For myself</strong><small>Manage my own support</small></button></div><label className="field"><span>Full name</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="field-grid"><label className="field"><span>Email</span><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field"><span>Phone</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label className="field"><span>Password</span><input required type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><small>At least 10 characters.</small></label><button className="button auth-submit" disabled={busy}>{busy?'Creating account…':'Create account'}<ArrowRight/></button></form><p className="auth-register">Already registered? <Link to="/login">Sign in</Link></p></div></section></main>
}
